### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#109]
Next steps to implement first MVP of DeGitX:
 - [ ] Update the white-paper according to MVP: #103
 - [ ] Design metadata protocol: #104
 - [ ] Implement discovery protocol over metadata storage: #105
 - [ ] Implement metadata protocol over distributed DB: #106
 - [ ] Implement required Gitaly gRPC services for push and fetch: #107
 - [ ] Implement load balancing for fetch operations on front-end: #108
 - [ ] Implement 2PC coordination on front-end nodes: TBD
 - [ ] Implement 2PC with voting over git transaction hooks on back-end nodes: TBD
 - [ ] Create staging area, specify test scenarios, design benchmarking system: TBD
