### ISSUE TITLE
Week#42

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#35]
The plan for `#42` week:
 - [ ] Finish Gitlab staging setup: https://github.com/cqfn/degitx/issues/21
 - [x] Release binaries on tags: https://github.com/cqfn/degitx/issues/24
 - [x] Design node config file and create a parser: https://github.com/cqfn/degitx/issues/27
 - [x] Generate node ID based on public key: https://github.com/cqfn/degitx/issues/28
 - [ ] Research for metadata exchange protocols

Milestone https://github.com/cqfn/degitx/milestone/2
